# General
name: Big Data Framework
description: ""
url: https://the-engine-room.github.io/big-data-framework

markdown: redcarpet
highlighter: pygments

permalink: /:title

# Social share and comments.
disqus-id: yourusername
twitter: yourusername
github: yourusername
google: +yourusername

# RSS feed
rss-feed-limit: 10
rss-show-full: "no"